### ISSUE TITLE
Error when using Python 3

### ISSUE THREAD

**Issue by JustGlowing** [giordamaug/WisardClassifier-C_vectors#1]
Hi there,

I tried to run the example in `test.py` using python3.7 but I got this error:

```
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    wisard["A"] = PyDiscriminator(2,8)
  File "wisard_wrapper.pyx", line 35, in wisard_wrapper.PyDiscriminator.__cinit__
    self.thisptr = new Discriminator(bits, size, maptype)
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string
TypeError: expected bytes, str found
```

Any hint on how to make this work?

Regards

**Comment by JustGlowing** [comment]
Hi Maurizio,

I just submitted a pull request with a fix for the issue above.
